project:
  type: website
  output-dir: _render
  render:
    - "*.qmd"
    - "others/*.qmd"
    - "!handouts/day_2/Exercise4_RStudio.qmd"
  resources:
    - "handouts/"
    - "slides/"
    - "site_imgs/"
keywords: ["Competing Risks, Multi-State Models"]

website:
  title: "Competing Risks and Multi-State Models"
  description: ""
  site-url: "https://oucru-biostats.github.io/Competing_Risks-Multi-State_Models/"
  
  cookie-consent:
    type: express
    style: simple
    palette: dark
  google-analytics:
    tracking-id: "G-3EXJ6W4CBC"
    anonymize-ip: true
  favicon: "site_imgs/OUCRU.jpg"
  navbar:
    pinned: true
    logo: "site_imgs/OUCRU.jpg"    
    left:
      - href: index.qmd
        text: Home
      - href: others/other_resources.qmd
        text: Additional R Resources
        

  comments:
    giscus:
      repo: "oucru-biostats/Competing_Risks-Multi-State_Models"
      repo-id: "R_kgDOR-wuNg"
      category: General
      category-id: "DIC_kwDOR-wuNs4C6g_W"
      mapping: pathname
      reactions-enabled: true
      loading: lazy
      input-position: top
      theme: light # You can also use 'dark' or 'auto'
      

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2026 Ronald Geskus <br></span>
      <span class="faux-block">Contact: [rgeskus@oucru.org](mailto:rgeskus@oucru.org) <br></span>      
      <span class="faux-block">All content licensed under [Creative Commons CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)</span>
    center: |
     
    right: |
      <span class="faux-block"><a href="https://github.com/oucru-biostats/Competing_Risks-Multi-State_Models">View source on GitHub</a></span>

toc: true
number-sections: true

execute: 
  echo: true

format:
  html:
    theme: cosmo
    css: custom_styles.css       # Links your CSS globally
    toc: true
    toc-location: left          # Global TOC on the left
    toc-depth: 2
    number-depth: 2
    link-external-icon: true
    link-external-newwindow: true
    date-format: "MMMM D, YYYY"
    include-after-body: 
      - password_logic.html     # Injects the password popup globally