---
title: Introduction to R 2025, Day 2
author: "Ronald Geskus and Thinh Ong Phuc"
engine: knitr
format-links: 
  - html
toc: false
number-sections: false
webr:
  channel-type: "shared-array-buffer"
  cell-options:
    autorun: false
    message: true
    warning: true
    eval: true
    echo: false
format:
  revealjs:
    slide-number: true
    logo: "figures/OUCRU.jpg"
    preview-links: true
    theme: solarized
    transition: fade
    show-slide-number: print
    embed-resources: true
    include-in-header: 
      - text: |
          <script src='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/js/all.js'></script>
filters: 
  - webr
---

## Learning goals {.smaller} 

- Day 1
  - Basic structure of the R program and language
  - Use the RStudio working environment	
  - Import, inspect and manage a data set
    - Select variables (columns) and rows (observations)
	- Missing data, factors, dates

::: {.fragment .highlight-red}
- Day 2
  - Functions
  - Visualisations using graphics in base R
  - Object specific functions
  - Finding further information
::: 


# Functions

## Basic format {.smaller .scrollable}

- All actions are performed via functions: 
  `sqrt`, `mean`, `help`, `library`, `t.test`, `plot`

- Input: *required* and *optional* arguments; within parentheses, separated by comma
  - required: need to be supplied
  - optional: have default values

    Beware of sequence of arguments; required ones come first. Compare
	```{.r}
    log(1000, 10) 
    log(10, 1000) 
	```

::: {.fragment}
- Some functions have special "argument": `...`  
  Meaning: anything that makes sense. Example: in `c` and `paste` function, which allow for the use of many values to
- Output: result of calculations (typically assigned to R object), graphics, help
   window, etc.

- You can use functions within other functions, e.g. `mean(c(3,6,8))`
:::

## Functions: the inside {.smaller}

- Function code can be seen by leaving out the parentheses \texttt{( )}
```{webr-r}
IQR
```
- General structure: 

```{.r}
FunctionName(args) {
    lines of R code (collection of functions)
}
```

The last value is returned as output
- You can write your own functions:

```{webr-r}
good.morning <- function(work){
    if(work==TRUE) cat("wake up") else 
      cat("you can stay in bed")
}
good.morning()
```

# Basic data visualisation

## R graphics systems:

- Base graphics (package *graphics*)
  - Straightforward to use
  - Always loaded when R is started
  - See Ch.\ 12 of manual [An Introduction to R](https://cran.r-project.org/doc/manuals/R-intro.pdf){target="_blank"}
	
::: {.fragment}
- lattice package. Less popular nowadays. Not covered here. 
- **ggplot2** package: Wednesday morning
- Note: these systems cannot be mixed
- Each of these systems has many packages with extensions
:::

## Basic plot in base graphics {.smaller}


1. Plot fare paid as function of age
```{.r}
plot(titanic$age, titanic$fare)
```
What would you like to change to make it good enough for publication? 

::: {.fragment}

- Formula based specification
    - general form: `dependent ~ independent`
	```{.r}
    plot(fare ~ age, data=titanic)
    ```
    - independent: variable names separated by operator (mostly `+` and `*`)
    - functions with formula (as first argument) have `data` and `subset` argument
    - basis for specification of regression models
:::

::: {.fragment}

-  Good summary on base graphics on page 5 of [Reference card](http://cran.r-project.org/doc/contrib/Baggott-refcard-v2.pdf){target="_blank"}
:::

::: {.fragment}
*Some possible changes: change labels along axes, rotate numbers along y-axis, add regression line, rescale fare*
::: 

## Use base graphics for simple tasks

Example: explain logarithmic scale via graph

## Arguments and parameters that can be changed {.smaller}

- Within function only
  - `xlab`, `ylab`, `main`
  - `type`
  - `xlim`, `ylim`, `log`
  
- Also via `par` function
  - `cex.axis`, `cex.lab`, `las`
  - `cex`, `pch`
  - `col`, `lty`, `lwd`, `cex`

- Only via `par` function
  - `mar`, `mfcol`, `mfrow`


## Some important functions for plotting ##

- High level plot functions
  - `plot`
  - `hist`
  - `boxplot`
  
- Low level plot functions (add to existing plot)
  - `points`
  - `lines`, `abline`
  - `text`, `legend`, `title`, `arrows`, `segments`

## Other plots

1. Plot fare paid as function of age
```{.r}
plot(titanic$age, titanic$fare)
```

2. Make a histogram of age

::: {.fragment}
3. Make a boxplot of fare by passenger class. 
  
4. There are high values for fare that disturb the plot. Therefore, only show the
fare up to 300 British Pounds.
:::



## Export: two types of formats {.smaller}

- Vector format (pdf, eps, wmf, emf, svg)
  - digital image consisting of independent geometric objects
        (segments, polygons, curves, etc.)
  - can be enlarged without losing resolution
- Raster (png, jpeg, tiff, bmp).
  - rectangular grid of pixels, possibly with color
  - resolution impaired if image is enlarged
- Graphics can be saved via the menu in the graphics/plots window, or
    a specific graphics file type can be created directly via code

```{.r}
pdf("foo.pdf",...)
...
dev.off()
```
or `win.metafile("foo.wmf",...)` or `png("foo.png",...)` and ending with `dev.off()`
	
	
# Some further topics about R

## Structure of R program {.smaller}

- Everythin created and stored is an **object**: data, functions, results analysis if assigned within R session

::: {.fragment}

- **Environment**: a collection of objects that is accessible in R session
  1. **Workspace**: objects we create/import in RStudio: **Global Environment** in
        **Environment** pane
  2. Packages with existing functions and data sets: **base**,
        **stats**, **graphics**
  3. When a package is loaded in R session, a new environment is created

     Listing of environments shown in RStudio via drop-down list under **Global
    Environment** in **Environment** pane
- Hierarchical structure of environments; needed for dealing with masked objects due
to duplicate names
:::

## R resembles operating system

| R                               |  operating system           |
|---------------------------------|-----------------------------|
| objects                         | files                       |
| Workspace                       | current folder              |
| environments                    | folders in "path" variable  |
| **Environment** pane in RStudio | Explorer window             |


## Object specific functionality (I)

- Output of function depends on *class* of object

Examples:

-   `summary`:  
  `summary.data.frame`, `summary.factor`, `summary.Date`  
   default: `summary.default`
-  `plot`: `plot(y ~ x, data=..., ...)`
  
        Plot depends on class of `x`: scatterplot is default, but
        boxplot if `x` is of class factor and plot by year if `x` is of class date

## Object specific functionality (II)

Why important to know?

- Finding information in help file
- Very efficient in use. E.g. `plot` is a *generic function*, with specific methods
    depending on the class of the object that is the argument of the function.  
	*We only need to remember `plot`*

## Another object mode: list {.smaller .scrollable}

- General mode to store information
- Modes cannot be mixed in vectors
```{webr-r}
teacher <- c("Ronald","Thinh","Tuyen")
room <- c(306,305,305)
c(teacher, room)
```
- Modes can be mixed in a list:

```{webr-r}
list(teacher, room)
list(teacher = teacher, room = room)
```
Two *components*, with names `teacher` and `room` 

- Data are of mode list, but with a special class `data.frame`
```{.r}
mode(titanic)
class(titanic)
```

## Finding Information {.smaller}

-   Function `help`. R is object oriented!

-   Search on Google (using `language r:`)

-   chatGPT or an R package such as
    [askgpt](https://www.johannesbgruber.eu/post/2023-04-02-introducing-askgpt-a-chat-interface-that-helps-you-to-learn-r/){target="_blank"}
    or [ellmer](https://cran.r-project.org/web/packages/ellmer/index.html){target="_blank"}

-   [R documentation](https://www.rdocumentation.org){target="_blank"}  
[Rseek](http://rseek.org){target="_blank"}

-   [R-universe](https://r-universe.dev/search){target="_blank"}

-   CRAN ([list with packages](https://cloud.r-project.org/){target="_blank"}, [Task Views](https://cran.r-project.org/web/views/){target="_blank"}, [FAQs](https://cran.r-project.org/faqs.html){target="_blank"}, Vignettes)

    [CRANsearcher](https://github.com/RhoInc/CRANsearcher){target="_blank"} in RStudio

-   [Stack Overflow](http://stackoverflow.com/questions/tagged/r){target="_blank"}

-   Have a look at the links provided at the end of the handout

## Exercise

Find information on 

- descriptive statistics
- change several categorical variables into factor
- recognize nonstandard date formats

## The apply  functions

- `apply`: apply a function over all columns or all rows of a data.frame

- `lapply`: apply a function over a list

- `sapply`: similar to `lapply` but more user-friendly if output can
    be coerced into a vector

- `tapply`: can be used to split a vector in subgroups and apply a
    function to each of the subgroups

## Exercise

- Make a summary of age by passenger class
- 
